### ISSUE TITLE
Document PHP 5.4 Requirement

### ISSUE THREAD

**Issue by cooperfellows** [ucfcdl/UDOIT#10]
Hi There,

This tools looks great, we are planning to implement it in the coming weeks/months. When demoing it on one of our servers, I realized it requires PHP 5.4. Is this documented somewhere? If not, I'd suggest adding it to the (otherwise excellent) install instructions. If this is documented somewhere, please forgive me!

Thanks.

~ Cooper

**Comment by bagofarms** [comment]
Sorry about the delayed response.  I guess i had email notifications turned off.  The 5.4 requirement has been documented in the README file.

**Comment by cooperfellows** [comment]
Oh no worries Jacob, I saw the updated project page. We spun up a new
server with 5.4 installed anyway.

The tool is working very well so far, thanks for all your effort. I will be
sure to contribute where I can.

~ Cooper
