### ISSUE TITLE
Color Contrast tool not working in most cases

### ISSUE THREAD

**Issue by adrian-goetz** [ucfcdl/UDOIT#132]
I found the following issues in the color modifying tool:

- [x] The Submit button is not enabled unless you select a color from the long pallet at the bottom.
- [ ] Would not let me edit files: would have a 500 error upon clicking Submit.
- [ ] After selecting a color from the pallet at the bottom, you can Submit and it will say the changes are made. However, if you have also selected to bold or italicize the text, it will not make that change. It says the change was made, but it does not transfer to the page.

**Comment by bagofarms** [comment]
Submit button issue fixed.  The bold issue seems intermittent depending on the HTML (it works for me, but not in all cases).

Editing files is being taken care of in a separate case.
