### ISSUE TITLE
Undefined Constant GA_TRACKING_CODE - Heroku Deployment

### ISSUE THREAD

**Issue by cooperfellows** [ucfcdl/UDOIT#137]
When deploying to heroku, the herokuConfig.php file is used. This file is missing the new Google Analytics tracking code constant that was introduced in commit [#8d12779](https://github.com/ucfcdl/UDOIT/commit/8d127794df55f1c064e894be89393e256c3dec7a). 

This variable is assumed to exist in the template.php file, and throws a warning when accessing UDOIT from a Heroku deployment:
![image](https://cloud.githubusercontent.com/assets/6798541/14748109/ed2ee24a-0885-11e6-946d-53aed7c75c75.png)

This constant should probably be introduced in the settings.php file. That way, regardless of the deployment type, the constant will be available.

**Comment by bagofarms** [comment]
Fixed in #138
