### ISSUE TITLE
Heroku Database Configuration Error

### ISSUE THREAD

**Issue by cooperfellows** [ucfcdl/UDOIT#139]
The database configuration for Heroku is incompatible with the insert expression used in[ process.php on line 138](https://github.com/ucfcdl/UDOIT/blob/master/public/process.php#L138). It is attempting to insert the `CURRENT_TIMESTAMP` into a column that has been defined as a `bigint` during the table creation.

The output of the error is:
`ERROR: column "date_run" is of type bigint but expression is of type timestamp with time zone LINE 6: ($1, $2, $3, CURRENT_TIMESTAMP, $4, $5) ^ HINT: You will need to rewrite or cast the expression.`

I suggest changing the database creation file ([db_pg_setup.php](https://github.com/ucfcdl/UDOIT/blob/master/db_pg_setup.php#L9)) so the reports SQL creation query looks like this:

> $reports_sql = "CREATE TABLE IF NOT EXISTS {$db_reports_table} (
>   id SERIAL PRIMARY KEY,
>   user_id integer,
>   course_id integer,
>   file_path text,
>   date_run timestamp with time zone,
>   errors integer,
>   suggestions integer
> );";

Additionally, the HEROKU.md file should be updated to switch out `bigint` for `timestamp with timezone` as mentioned above.

After making these changes, I am able to deploy effectively using Heroku. Reports are saving, PDF's are generating, etc...

**Comment by bagofarms** [comment]
Thank you so much for this info!  We'll make those changes.

**Comment by cooperfellows** [comment]
Your welcome. Thanks for the work on the tool! My commits around this one are a bit messy, otherwise I would send through a pull request. I will be sure to keep it clean next time around.

Do you have any specific guidelines around commit messages/pull requests etc... that I can follow the next time I want to work on something?

**Comment by bagofarms** [comment]
We don't really have a style guide to follow.  Just the basics like descriptive commit messages and no commented-out code.

I see you just submitted a pull request.  I'll review it and merge it now.
