### ISSUE TITLE
For the Synchronized Captions error, embed the video in an iframe for the preview.

### ISSUE THREAD

**Issue by bagofarms** [ucfcdl/UDOIT#17]
Currently, it just displays videos however they would be displayed in the page.  If the content creator just pasted a link to the video, UDOIT will show a link.  If the creator inserted the iframe code for the video into the page, it will show up in an iframe.  Make it show up in an iframe always.

**Comment by techrangerfj** [comment]
Issue resolution merged to master in pull request 33
