### ISSUE TITLE
UDOIT logo references UCF servers even though logo file is in /assets/img

### ISSUE THREAD

**Issue by bedmison** [ucfcdl/UDOIT#63]
The UDOIT logo is loaded here: 

https://github.com/ucfcdl/UDOIT/blob/master/assets/css/main.css#L24 

but the URL provided is an absolute path to the UCF servers. The asset is included in the project in /assets/img , and should probably be referenced instead. Will reduce traffic on UCF servers and reduce outside dependancies.

**Comment by techrangerfj** [comment]
@bedmison thanks for the heads up, a pull request is now in for this change.
