### ISSUE TITLE
Add throbber to "Safe report as PDF" button while the PDF is generating

### ISSUE THREAD

**Issue by bagofarms** [ucfcdl/UDOIT#74]

**Comment by cooperfellows** [comment]
This does not work with the Heroku deployment, it results in a 404 when looking for the progress file:
![image](https://cloud.githubusercontent.com/assets/6798541/14787858/510e8dd4-0ad3-11e6-971c-cf1c6846cb07.png)

So the spinner never finishes, as can be seen in this video:
- http://screencast.com/t/XK1aZEdsfIML

Why is the `parsePdfProgress.php` file located in the lib directory and not in the public directory somewhere?
