### ISSUE TITLE
"View the source of this issue" disappears when expanding suggestion

### ISSUE THREAD

**Issue by robfentress** [ucfcdl/UDOIT#78]
When I click the link to "View the source of this issue" for a Suggestion (but *not* for an Error) the text of the link disappears, leaving only the number "1."
![screen shot 2015-12-09 at 1 52 52 pm](https://cloud.githubusercontent.com/assets/9356499/11695395/e45c9856-9e7c-11e5-81e6-f06405b66883.png)

**Comment by techrangerfj** [comment]
@bagofarms I am having trouble duplicating this issue. Do you have a code snippet and/or course where this issue can be seen?

**Comment by robfentress** [comment]
Unfortunately, this was encountered in a test environment which I cannot add others to.  We are evaluating UDOIT for use in production.  Basically, the error occurred when there was a "click here" link in a "page" in the "Pages" tool, as shown in the source in the screen capture.  However, it seems like anything that triggers a suggestion has this same issue.  Below the suggestion, <q>Link text should be descriptive</q>, you see the expanded source, with the empty list item that just says <q>1. </q>  The suggestion below that, <q>Synchronized captions should be provided for prerecorded web-based video</q> show what the list item says before it is expanded, namely, <q>1. View the source of this issue</q>.

**Comment by ssilverm** [comment]
What OS / Browser are you using?

**Comment by robfentress** [comment]
OS X El Capitan / Chrome

On Thu, Dec 10, 2015 at 3:56 PM, Shea <notifications@github.com> wrote:

> What OS / Browser are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ucfcdl/UDOIT/issues/78#issuecomment-163746975>.
>



-- 
Robert Fentress
Senior Accessibility Solutions Designer
540.231.1255

Technology-enhanced Learning & Online Strategies
Assistive Technologies
1180 Torgersen Hall
620 Drillfield Drive (0434)
Blacksburg, Virginia 24061

**Comment by bagofarms** [comment]
@robfentress We're unable to replicate the issue with the same combination of OS/browser.  What version of UDOIT are you using?

**Comment by robfentress** [comment]
@bagofarms Our sysadmin is seeing if he can find the version number, but he says the version was latest build as of 26 Oct.

**Comment by bagofarms** [comment]
@robfentress I believe we changed the way those links are displayed since you last updated UDOIT.  Check out our latest releases.  I'm going to close this issue, but please reopen it if you are still experiencing the issue on a newer version of UDOIT.
