### ISSUE TITLE
Using UFIXIT when there are multiple of the same type of error on the page adds "Fixed" to all of the errors.

### ISSUE THREAD

**Issue by bagofarms** [ucfcdl/UDOIT#8]
<img width="351" alt="screenshot 2015-07-10 14 42 20" src="https://cloud.githubusercontent.com/assets/1225334/8626593/6ea744e8-2713-11e5-8f42-b56ca65bca30.png">

**Comment by techrangerfj** [comment]
Resolution merged to master. See commit #0a2302fce225bccdc1635979c59546eba86da727

**Comment by techrangerfj** [comment]
Resolution merged to master. See commit #0a2302fce225bccdc1635979c59546eba86da727
