### ISSUE TITLE
Alt error should be suggestion

### ISSUE THREAD

**Issue by robfentress** [ucfcdl/UDOIT#85]
I get an error when I have an image with an empty alt attribute.  While a suggestion might be appropriate, since Canvas automatically populates the alt attribute with the image file name, it is a pretty safe assumption that if there is an empty alt atrribute, it is there intentionally.  Providing an empty alt attribute, as opposed to not having one at all, is a way to keep screen readers from voicing that there is an image at all (http://www.w3.org/TR/2015/NOTE-WCAG20-TECHS-20150226/F39).  This is something you may want to do if the image is purely decorative, or for certain other reasons.

The example image below is just to show that it is, indeed, triggered by an empty alt attribute, rather than being a statement on whether a logo should have alt text.
![screen shot 2016-01-07 at 3 46 01 pm](https://cloud.githubusercontent.com/assets/9356499/12182542/c7a4562c-b556-11e5-83a6-c2fd038e9cce.png)

**Comment by robfentress** [comment]
Any progress on this?  I'd like to be able to let faculty know that they can null the alt attribute to hide decorative images, but I worry, because of this, they will get confused.

**Comment by bagofarms** [comment]
@robfentress this should be fixed in master now.
