### ISSUE TITLE
Large text fails cssHasTextContrast incorrectly

### ISSUE THREAD

**Issue by robfentress** [ucfcdl/UDOIT#86]
Text with font-size:18pt with color:#7c7cff and background-color:#ffffff fails the check cssHasTextContrast, when it should pass.  There are different contrast requirements for non-bold large text (18pt and above must meet 3:1) than smaller text (4.5:1).  Text styled this way correctly passes both WebAI 's Color Contrast Checker (http://webaim.org/resources/contrastchecker/) and HTML_CodeSniffer (http://squizlabs.github.io/HTML_CodeSniffer/).  The relevant WCAG success criteria is "Contrast (Minimum): Understanding SC 1.4.3" (http://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html).

![screen shot 2016-01-08 at 9 48 39 am](https://cloud.githubusercontent.com/assets/9356499/12200659/24e63a98-b5ee-11e5-9931-57e8d28f8a2f.png)

**Comment by bagofarms** [comment]
Very good point (pun intended)!  I'll mark it as a bug.

**Comment by robfentress** [comment]
Not sure if this is the same issue as in your code, but this may be of interest to you:
[HTML_Code_Sniffer Bug Report "insufficient contrast error incorrectly given for 14pt bold text #155"](https://github.com/squizlabs/HTML_CodeSniffer/issues/155)
