### ISSUE TITLE
"No table headers found" in a table that already has headers (see comments for sample code)

### ISSUE THREAD

**Issue by bagofarms** [ucfcdl/UDOIT#9]
<table style="width: 551px; margin-left: auto; margin-right: auto;" border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<th style="text-align: center;" width="84">
<p>Week/Dates</p>
</th>
<th width="53">
<p>Mode</p>
</th>
<th width="113">
<p>Topic</p>
</th>
<th width="144">
<p>Assignments</p>
</th>
<th width="157">
<p>Due Dates</p>
</th>
</tr>
<tr>
<td width="84">
<p>Week 1</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;Course Orientation</p>
</td>
<td valign="top" width="144">
<p>Syllabus Quiz</p>
</td>
<td valign="top" width="157">
<p>&nbsp;<span>8/31 at 11:55pm EST</span></p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 2</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td valign="top" width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 3</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 4</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 5</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 6</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 6</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 7</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p><strong>Midterm Exam</strong></p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 8</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 9</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>&nbsp;</p>
</td>
<td valign="top" width="113">
<p>Spring Break</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 10</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 11</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 12</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 13</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 14</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 15</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>F2F</p>
</td>
<td valign="top" width="113">
<p>&nbsp;</p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td width="84">
<p>Week 16</p>
<p>&nbsp;</p>
</td>
<td valign="top" width="53">
<p>Online</p>
</td>
<td valign="top" width="113">
<p><strong>Final Exam</strong></p>
</td>
<td valign="top" width="144">
<p>&nbsp;</p>
</td>
<td width="157">
<p>&nbsp;</p>
</td>
</tr>
</tbody>
</table>

**Comment by bagofarms** [comment]
Same issue in this course:  https://webcourses.ucf.edu/courses/1043472/pages/mobile-device-and-apps-glossary

**Comment by techrangerfj** [comment]
It appears that the test that triggers this error is 'tableThShouldHaveScope'. The text describing the error is misleading though as it does not mention scope. The following changes will be made to the verbiage of the error:

Old
Title: No row or column headers found in table
Description: Table headers organize and define table data by row/column for sighted and [screen reader](http://en.wikipedia.org/wiki/Screen_reader) users.
----------------------------------------------------------------------------------------------------------------------------------------
New
Title: No row or column scopes declarations found in headers of the table
Description: Scope declarations in headers organize and define table data by row/column for sighted and [screen reader](http://en.wikipedia.org/wiki/Screen_reader) users.

**Comment by techrangerfj** [comment]
Resolution merged

**Comment by techrangerfj** [comment]
Resolution merged
