### ISSUE TITLE
U FIX IT erroneously says it has "Fixed!" color contrast

### ISSUE THREAD

**Issue by robfentress** [ucfcdl/UDOIT#94]
Using U FIX IT for fixing color contrast gives misleading feedback.  Basically, you can enter anything in the field for the hex color value, like "foo" or the same color as the background, and it will indicate it is "Fixed!" Running the whole scan over again, still correctly throws an error though.

![screen shot 2016-02-24 at 12 10 33 pm](https://cloud.githubusercontent.com/assets/9356499/13293948/c9eee640-daef-11e5-9836-92e63c7d1739.png)

![screen shot 2016-02-24 at 12 10 57 pm](https://cloud.githubusercontent.com/assets/9356499/13293955/d03a5c46-daef-11e5-9c9a-f3af9abd1d87.png)

**Comment by bagofarms** [comment]
I'm going to close this issue and open a more generic one stating that the phrasing should be changed to "Done!" and to provide a different response in the event of an issue.

**Comment by bagofarms** [comment]
Checking the color contrast to make sure it is actually accessible is part of another pull request and issue, so i think that will be covered in the future.
