### ISSUE TITLE
Change response from UFIXIT

### ISSUE THREAD

**Issue by bagofarms** [ucfcdl/UDOIT#96]
The current response to using UFIXIT is to display a small green box that says "Fixed!"  This might not always be the case.  The user might have used UFIXIT in an attempt to fix the issue, but it might still be inaccessible.  Instead, this should say "Done!" to be more generic and not to imply that the issue was actually fixed.

Also, UFIXIT should detect if there was an error during the fixing process, and respond with "There was an error" or something to that effect.  An error should also be displayed if input validation fails (issue #95 )

**Comment by techrangerfj** [comment]
This was implemented in pull request #109
